language: python
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m pytest --cov-report term-missing --cov=.
after-success:
  - bash < (curl -s https://codecov.io/bash)
